#include <stdio.h>

int main(int argc, char *artv[])
{
  puts("Hello world.");
  puts("You may be traveling across the world, but you’re still just a hangout away. With Google+, you can stay in touch over video chat.");
  puts("When you’re too tired to think straight, just open Google Now and find your hotel card with information about your reservation.");
  puts("The July 5 attack near Latakia was the fourth known Israeli airstrike in Syria this year.     Providing new details, American officials said that it had been carried out by Israeli aircraft that flew over the eastern Mediterranean, fired air-to-ground missiles and never entered Syrian airspace. The route of the Israeli aircraft led to some erroneous reports that the attack had been carried out by an Israeli submarine. In addition to targeting the Yakhont missiles, Israel carried out an airstrike in late January aimed at another system provided by Russia: a convoy of SA-17 surface-to-air missiles that Israeli officials believed were destined for Hezbollah.Iran’s arms shipments are also a concern for the Israelis.  In May, Israeli warplanes conducted two days of airstrikes that targeted, among other things, a shipment of Fateh-110 missiles — mobile surface-to-surface missiles that had been provided by Iran and flown to Damascus, Syria, on transport planes that passed through Iraqi airspace.  The Fateh-110 missiles, which the Israelis feared were also intended for Hezbollah, have the range to strike Tel Aviv and much of Israel from southern Lebanon. Iran has sent members of its paramilitary Quds force into Syria, under the supervision of Maj. Gen. Hossein Hamdani, a senior officer of the force who is in charge of operations in Syria and oversees Iran’s arms shipments to Hezbollah, according to American intelligence officials. Hezbollah’s attempt to acquire weapons is supervised by Shaykh Salah, a senior official in charge of the militia’s operations in Lebanon, according to American officials. Iran has also pressed Iraqi Shiites to join the fight in Syria in support of the Assad government. That includes about 200 members of the Badr Corps, Iraqis who were supported by Iran during Tehran’s long war against Saddam Hussein, and who later returned to Iraq after he was ousted from power, American officials say. The support of Iran and Hezbollah for the Assad government, and Israel’s military interventions, reflects how the conflict has drawn in outside powers. Both Saudi Arabia and Qatar have been arming the Syrian rebels, and Congress recently dropped objections to a proposal by President O");
  puts("They are not using these objects, of course, but clicking on the pictures of them in popular word-processing programs like Microsoft Word or Google Docs. The icons linger like vestigial organs of an old-style office, 31 years after I.B.M.’s personal computer brought work into the software age. They symbolize an old style of office software, built for the time when the desktop computer was new and unfamiliar. But no longer are workers tethered to a desk, or even to an office; we are all toting around laptops, tablets and smartphones to make every place a workplace. And so office software is changing. These days, what is important is collaboration, small screens, fast turnarounds, social media and, most of all, mobility. 'The way people use things is fundamentally changing,' said Bret Taylor, chief executive of Quip, a start-up offering document-writing software that focuses more on mobile than desktop work.  Mr. Taylor, 33, is one of the best-regarded young software engineers in Silicon Valley. He helped create Google Maps before serving as Facebook’s chief technical officer. His co-founder, Kevin Gibbs, also 33, helped create Google’s data centers and as a side project developed the software that suggests completions when people start to type questions into Google search. Their company is one of several that is developing office software for the mobile world. Some of the new programs still borrow from images of old-fashioned work in their design. But the capabilities they offer are decidedly up-to-date. Last month Box, an online service for storing documents, pictures and other data, bought Crocodoc, a company that makes it possible to view Microsoft Word documents and other popular file formats across a variety of devices at the right size for whatever screen is being used at the time. Evernote, another online storage outfit, allows people to write, edit and share notes together, instead of e-mailing multiple versions of a Word document to one another. Sam Schillace, Box’s vice president for engineering, wrote the original program that became Google Docs, which was introduced only six years ago. He explained that in a mobile world, where everyone is in nearly constant contact, speed and ease of use are more important than lots of font choices. We were guilty of taking the existing nature of documents, he said, but six years ago connectivity was a question. Now everything is connected all the time. Both Microsoft and Google are scrambling to make their products reflect a work environment where PCs exist alongside other devices. There is a mobile version of Microsoft Office, which includes Microsoft Word, but it can only be used to edit certain kinds of documents and collaboration is limited. One reason for this, the company says, is that it does not want to force its user base to relearn too much, too quickly.We have one billion users of Office,said Julia White, general manager of Office marketing.");
  return 0;
}
